### ISSUE TITLE
Thanks and suggestions

### ISSUE THREAD

**Issue by rod-farias** [olton/HtmlToJS#1]
Good work, Olton. The library is very fast and very easy to use. I imagine it will be at the core of MetroUI.

I have two suggestions:
1. Please add at least one slightly more complete case in Readme.md, for example:

`h1("This` is a title", {id: "myTitle", className: "class-1", style:{"font-size":"11pt", "color": "red"} } )

2. This is just a suggestion to decrease the file size. You can create a utility function like

```
function getArg(arg, idx, def)
{
    return arg.length > idx && arg[idx]!==undefined ? arg[idx]: def;
}
```
and then replace all lines

`var xxx = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : {};
`

for
```
var xxx = getArg(arguments, 2, {}};
var yyy = getArg(arguments, 0, 'h1'};
var zzz = getArg(arguments, 1, []};

```

There is probably some performance difference, but function calls in javascript loops are usually negligible, and on the other hand the render.js file whas shortened in my case from 55Kb to 42Kb.

Thanks again,

Rodrigo

**Comment by olton** [comment]
Hi Rodrigo!

I added point one to the readme.

Regarding point 2. This code generates the builder, in this case, it's `rollup`. And I have no influence on this. The assembly depends on the settings for which browsers the assembly is going on.

**Comment by rod-farias** [comment]
Sure.
Sorry but I'm not handling well with the new "compiled" javascript, I'm 10 years out of date.

I've been playing with RenderJS and it's amazing how easy it is to learn. The rendering is instantaneous, a table with 5 x 100K cells in 0.4 secs.

I don't know if I will write html again.

**Comment by olton** [comment]
I will be grateful if you will star the project on GitHub and tell your friends about it :)

**Comment by olton** [comment]
@rod-farias project moved to https://github.com/olton/htmljs
